### ISSUE TITLE
Add bypass perms for admins/ops

### ISSUE THREAD

**Issue by Greaper88** [DoctorMacc/GeyserPreventServerSwitch#2]
While it may be ideal to block regular players from certain servers, sometimes an admin may be stuck on their bedrock account and needs to go to a blocked server to administrate. It would be cool to have a bypass perm that can be added to admin groups so that admins can still get to the blocked servers.

**Comment by Camotoy** [comment]
Resolved in 92a2ff470693478dbb7302cf44d1f41b957f5d19.
